/**
 * Generate Romanian + Russian explanation overlays for the question bank using
 * the DeepL API (free tier). Only the `explanation` text is translated; question
 * text and answer choices stay in English to match the real assessment.
 *
 * Run from the `app/` folder:
 *
 *   DEEPL_API_KEY=your-key-here npx tsx scripts/translate-explanations.ts
 *
 * The key is read from the environment — never commit it. Free-tier keys end in
 * ":fx" and use the api-free.deepl.com host (handled automatically below).
 *
 * Output (overwritten each run):
 *   src/data/explanations.ro.ts
 *   src/data/explanations.ru.ts
 */
import { readFileSync, existsSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { questions } from '../src/data/questionBank';

/**
 * Resolve the DeepL key from (in order): process env, app/.env.local, app/.env.
 * .env.local is git-ignored — keep the key there, never commit it.
 */
function resolveApiKey(): string | undefined {
  if (process.env.DEEPL_API_KEY) return process.env.DEEPL_API_KEY;
  const here = dirname(fileURLToPath(import.meta.url));
  for (const file of ['.env.local', '.env']) {
    const path = join(here, '..', file);
    if (!existsSync(path)) continue;
    const match = readFileSync(path, 'utf8').match(/^\s*DEEPL_API_KEY\s*=\s*(.+?)\s*$/m);
    if (match) return match[1].replace(/^["']|["']$/g, '');
  }
  return undefined;
}

const API_KEY = resolveApiKey();
if (!API_KEY) {
  console.error('Missing DEEPL_API_KEY. Add it to app/.env.local or run: DEEPL_API_KEY=your-key npx tsx scripts/translate-explanations.ts');
  process.exit(1);
}

// Free-tier keys end in ":fx" and must hit the api-free host.
const API_HOST = API_KEY.endsWith(':fx') ? 'https://api-free.deepl.com' : 'https://api.deepl.com';
const BATCH_SIZE = 40;

type Target = { lang: 'RO' | 'RU'; varName: string; file: string };

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, '..', 'src', 'data');

const targets: Target[] = [
  { lang: 'RO', varName: 'explanationsRo', file: join(dataDir, 'explanations.ro.ts') },
  { lang: 'RU', varName: 'explanationsRu', file: join(dataDir, 'explanations.ru.ts') },
];

const ids = questions.map((q) => q.id);
const sourceTexts = questions.map((q) => q.explanation);

async function translateBatch(texts: string[], targetLang: Target['lang']): Promise<string[]> {
  const res = await fetch(`${API_HOST}/v2/translate`, {
    method: 'POST',
    headers: {
      Authorization: `DeepL-Auth-Key ${API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      text: texts,
      source_lang: 'EN',
      target_lang: targetLang,
      preserve_formatting: true,
    }),
  });
  if (!res.ok) {
    throw new Error(`DeepL ${targetLang} failed: ${res.status} ${await res.text()}`);
  }
  const data = (await res.json()) as { translations: { text: string }[] };
  return data.translations.map((t) => t.text);
}

async function translateAll(targetLang: Target['lang']): Promise<string[]> {
  const out: string[] = [];
  for (let i = 0; i < sourceTexts.length; i += BATCH_SIZE) {
    const batch = sourceTexts.slice(i, i + BATCH_SIZE);
    process.stdout.write(`  ${targetLang}: ${i + batch.length}/${sourceTexts.length}\r`);
    out.push(...(await translateBatch(batch, targetLang)));
  }
  process.stdout.write('\n');
  return out;
}

function renderFile(varName: string, lang: string, translations: string[]): string {
  const entries = ids
    .map((id, idx) => `  ${JSON.stringify(id)}: { explanation: ${JSON.stringify(translations[idx])} },`)
    .join('\n');
  return (
    `import type { QuestionTranslation } from '../types/question';\n\n` +
    `// ${lang} explanation overlays, keyed by question id.\n` +
    `// AUTO-GENERATED by scripts/translate-explanations.ts — do not edit by hand.\n` +
    `export const ${varName}: Record<string, QuestionTranslation> = {\n${entries}\n};\n`
  );
}

async function main() {
  console.log(`Translating ${questions.length} explanations via DeepL (${API_HOST})...`);
  for (const target of targets) {
    const translated = await translateAll(target.lang);
    writeFileSync(target.file, renderFile(target.varName, target.lang, translated), 'utf8');
    console.log(`  wrote ${target.file}`);
  }
  console.log('Done. Review the output, then rebuild the app.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
