import type { QuestionTranslation } from '../types/question';

// RO explanation overlays, keyed by question id.
// AUTO-GENERATED by scripts/translate-explanations.ts — do not edit by hand.
export const explanationsRo: Record<string, QuestionTranslation> = {
  'nia-01-001': {
    explanation:
      'Cablurile de telecomunicații de interior dintr-o clădire obișnuită sunt de obicei clasificate Cca-s1b,d2,a2. Litera principală (Cca) descrie răspândirea flăcării; subratele s, d și a descriu producția de fum, picăturile de flăcări și aciditatea.',
  },
  'nia-01-002': {
    explanation:
      'Cifra "s" din notarea EuroClass indică producția de fum. s1a este cel mai scăzut nivel de fum disponibil, astfel încât B2ca s1a d1 a1 produce mai puțin fum decât alternativele s1b sau s2.',
  },
  'nia-01-003': {
    explanation:
      'Cablurile de date, telefonice și de alarmă împotriva intrușilor sunt cabluri de comunicații. Un cablu de rețea de 230 V este un cablu de alimentare de joasă tensiune și intră sub incidența instalației electrice, nu a instalației de telecomunicații.',
  },
  'nia-01-004': {
    explanation:
      'Instalarea externă introduce expunerea la UV și la intemperii. Materialul și clasificarea învelișului, nu doar categoria de date, decid dacă cablul este adecvat. BS EN 50174-3 acoperă cerințele de instalare externă.',
  },
  'nia-01-005': {
    explanation:
      'Legătura permanentă de clasă EA este limitată la 90 m. Cifra de 100 m este lungimea totală a canalului, care include legătura permanentă plus echipamentul și cablurile de conectare.',
  },
  'nia-01-006': {
    explanation:
      'Canalul reprezintă legătura permanentă plus cablurile de la fiecare capăt. Pentru clasa EA, lungimea totală a canalului este de 100 m, lăsând 10 m pentru cabluri deasupra legăturii permanente de 90 m.',
  },
  'nia-01-007': {
    explanation:
      'În cazul în care lungimea totală a cablului depășește 20 m, toleranța de canal pentru cablajul fix este redusă la 95 m pentru a menține pierderea de inserție în limitele bugetului clasei EA.',
  },
  'nia-01-008': {
    explanation:
      'Dulapurile mai mici (≤21U) necesită cel puțin un conductor de legătură de protecție de 4 mm² conform HD 60364-5-54. Cadrele mai mari necesită un conductor de 16 mm².',
  },
  'nia-01-009': {
    explanation:
      'Pentru rafturile mai mari (>21U), standardul HD 60364-5-54 prevede cel puțin un conductor de legătură de 16 mm². Același standard stă la baza normelor BS 7671 privind legarea la pământ și la pământ.',
  },
  'nia-01-010': {
    explanation:
      'Un dulap de perete 12U se încadrează în suportul pentru dulapuri mici (≤21U), astfel încât conductorul de legătură minim de 4 mm² se aplică indiferent de materialul ușii.',
  },
  'nia-01-011': {
    explanation:
      '100baseT rulează pe o pereche torsadată echilibrată, cum ar fi Cat5e. 100baseSX este optic, în timp ce 10base2 și 10base5 sunt variante Ethernet coaxiale tradiționale.',
  },
  'nia-01-012': {
    explanation:
      'Categoriile de cupru echilibrat, cum ar fi Cat 6A, Cat 7 sau Cat 8, sunt limitate la aproximativ 100 m la 10 Gb/s. La 500 m, fibra este familia media corectă.',
  },
  'nia-01-013': {
    explanation:
      'Fibrele multimodale sunt destinate pentru distanțe scurte, de obicei câteva sute de metri la 10 Gb/s. Pentru legăturile de 10 Gb/s la scară kilometrică, se utilizează fibra monomodală.',
  },
  'nia-01-014': {
    explanation:
      '9/125 µm este monomod; 50/125 µm și 62,5/125 µm sunt multimodale. 100/125 nu este o dimensiune standard recunoscută pentru fibra de telecomunicații.',
  },
  'nia-01-015': {
    explanation:
      'CPR se referă la Regulamentele privind produsele de construcție, care stabilesc cadrul pentru declararea performanței produselor de construcție, inclusiv performanța de reacție la foc pentru cabluri.',
  },
  'nia-01-016': {
    explanation:
      'O declarație de performanță este documentul în care un producător menționează caracteristicile declarate ale unui produs de construcție, inclusiv orice rating EuroClass de reacție la foc.',
  },
  'nia-01-017': {
    explanation:
      'Marcajul CE este un marcaj de conformitate care acoperă directivele sau reglementările UE relevante care se aplică clasei de produse respective. Nu este o declarație de origine și nu este o aprobare la nivel mondial.',
  },
  'nia-02-001': {
    explanation:
      'Pentru cablajul echilibrat cu 4 perechi, BS EN 50174-2 utilizează 8× diametrul exterior ca ghid al razei de curbură instalată. Curbele mai strânse afectează diafonia și pierderea de retur.',
  },
  'nia-02-002': {
    explanation:
      'Pentru fibră și coaxial, BS EN 50174-2 utilizează 10× diametrul exterior al cablului ca referință a razei de curbură instalată. Valorile producătorului pot fi mai stricte pentru tragerea pe termen scurt, dar curbele instalate trebuie să respecte standardul.',
  },
  'nia-02-003': {
    explanation:
      '1U pe un rack de 19 inch are 44,45 mm (1,75 inch) înălțime. Echipamentul montabil în rack este dimensionat în unități de rack întregi (1U, 2U, 4U etc.).',
  },
  'nia-02-004': {
    explanation:
      'Un sistem de gestionare a cablurilor acoperă întreaga gamă de produse de cale concepute pentru a conține sau a susține cablurile, inclusiv conductele și tuburile pentru instalarea suflată. Ambalajul de transport nu este un sistem de management.',
  },
  'nia-02-005': {
    explanation:
      'Grilele tavanului suspendat nu sunt dimensionate pentru a suporta încărcăturile traseelor de cabluri. Containerul trebuie să fie fixat pe structura în sine, astfel încât grila tavanului să își suporte doar propria greutate.',
  },
  'nia-02-006': {
    explanation:
      'Adăugarea cablurilor crește greutatea și poate depăși sarcina proiectată a incintei și a dispozitivelor sale de fixare. Sarcina trebuie verificată înainte de introducerea cablurilor suplimentare.',
  },
  'nia-02-007': {
    explanation:
      'Căile de evacuare au cerințe specifice de siguranță împotriva incendiilor. Închiderea, fixarea și orice etanșare trebuie să fie selectate astfel încât ruta să rămână sigură în timpul evacuării sau în caz de incendiu.',
  },
  'nia-02-008': {
    explanation:
      'Un cablu prins sau zdrobit poate eșua testele de performanță și se poate deteriora în timp. Capacele trebuie să se închidă curat, fără presiune asupra cablurilor.',
  },
  'nia-02-009': {
    explanation:
      'Izolarea partajată trebuie să respecte separarea electrică, considerentele EMI, identificarea și orice politică a clientului. Traseul trebuie gestionat astfel încât un serviciu să nu compromită altul.',
  },
  'nia-02-010': {
    explanation:
      'Curbele în incintă nu trebuie să forțeze cablurile sub raza de curbură permisă. Accesoriile de îndoire furnizate de producător sunt concepute pentru a menține această geometrie.',
  },
  'nia-02-011': {
    explanation:
      'Izolatoarele tăiate la fața locului pot lăsa bavuri ascuțite care abrazează sau taie tecile cablurilor în timpul instalării și deplasării ulterioare. Buruienile trebuie îndepărtate sau acoperite cu o bucșă special concepută.',
  },
  'nia-02-012': {
    explanation:
      'Închiderea este la fel de sigură ca și fixările și fundalul acesteia. Substratul, sarcina și mediul influențează fixarea corectă.',
  },
  'nia-02-013': {
    explanation:
      'Legăturile prea strânse pot strivi cablul echilibrat și pot afecta performanța transmisiei. Legăturile trebuie să mențină fasciculul fără a modifica geometria cablului.',
  },
  'nia-02-014': {
    explanation:
      'Rutele de cablare în rețea trebuie să poată fi testate și întreținute. Recipientele trebuie instalate astfel încât capacele, îmbinările și punctele de acces să fie accesibile.',
  },
  'nia-02-015': {
    explanation:
      'Umiditatea și mediile chimice scurtează durata de viață a izolației neadecvate și pot slăbi suportul în timp. Gradul de izolare și de fixare trebuie să fie ales în funcție de mediu.',
  },
  'nia-02-016': {
    explanation:
      'Rosturile de dilatare există deoarece clădirea se mișcă. Izolația rigidă care traversează rostul va fi deteriorată în timp și poate transfera tensiunea asupra cablurilor.',
  },
  'nia-02-017': {
    explanation:
      'Izolatoarele metalice pot necesita legături de protecție în funcție de proiectare și de cerințele de siguranță electrică. Proiectarea electrică dictează strategia de lipire.',
  },
  'nia-02-018': {
    explanation:
      'Plăcile de tavan și elementele grilajului nu sunt suporturi pentru cabluri. Cablurile de deasupra tavanelor trebuie să treacă pe o tavă corespunzătoare, pe un coș sau pe o altă cale adecvată.',
  },
  'nia-02-019': {
    explanation:
      'Tava cu coșuri funcționează bine atunci când cablul este susținut uniform. Punctele de presiune ascuțite, stivuirea grea și căderea severă denaturează geometria cablului.',
  },
  'nia-02-020': {
    explanation:
      'Calitatea izolației afectează în mod direct siguranța, capacitatea de întreținere și performanța legăturii. Elementele de mai sus sunt defecte comune care ar trebui identificate înainte de predare.',
  },
  'nia-03-001': {
    explanation:
      'În timpul instalării, Cat 6A și UTP ecranat utilizează în mod normal o rază de îndoire de 4× diametrul exterior. Valoarea instalată (în serviciu) poate fi mai strânsă decât în timpul tragerii.',
  },
  'nia-03-002': {
    explanation:
      'Cablurile echilibrate cu performanțe superioare sunt mai sensibile la geometrie. Dintre cele patru categorii enumerate, Cat 6A are cea mai mare preocupare legată de raza de curbură.',
  },
  'nia-03-003': {
    explanation:
      'Pentru Cat 6A într-o conductă de 20 mm, exemplul este de 2 cabluri. Umplerea trebuie verificată întotdeauna în funcție de diametrul exterior al cablului, de curbe și de lungimea de tracțiune.',
  },
  'nia-03-004': {
    explanation:
      'canalele de 50 mm × 50 mm oferă un traseu ordonat și accesibil la înălțimea biroului pentru un pachet mic, cum ar fi 12 cabluri Cat 6. Celelalte sunt fie prea mici, fie supradimensionate pentru locul respectiv.',
  },
  'nia-03-005': {
    explanation:
      'Un mănunchi gestionat reduce frecarea și evită suprasolicitarea cablurilor individuale. Cablurile încrucișate sau răsucite cresc tensiunea de tragere și riscul de deteriorare.',
  },
  'nia-03-006': {
    explanation:
      'Lubrifianții incompatibili pot ataca chimic teaca cablului sau pot lăsa reziduuri care afectează terminarea ulterioară. Lubrifiantul aprobat de producător este alegerea corectă.',
  },
  'nia-03-007': {
    explanation:
      'O buclă de serviciu scurtă permite terminarea și reprelucrarea viitoare. Slack-ul trebuie să respecte raza de curbură și nu trebuie să depășească bugetul de lungime testat.',
  },
  'nia-03-008': {
    explanation:
      'Multe cabluri devin fragile sub temperatura limită de instalare. Tragerea unui cablu sub această temperatură poate fisura teaca și deteriora conductorii.',
  },
  'nia-03-009': {
    explanation:
      'Cablarea echilibrată respinge zgomotul de mod comun, dar nu este imună. Separarea adecvată, ecranarea și izolarea corespunzătoare reduc zgomotul indus.',
  },
  'nia-03-010': {
    explanation:
      'Traseele verticale lungi pot exercita o greutate semnificativă asupra terminației dacă nu sunt susținute. Suporturile intermediare previn tensionarea conectorilor și a conductorilor.',
  },
  'nia-03-011': {
    explanation:
      'Deschiderile aspre sau supradimensionate pot deteriora învelișul cablului. O garnitură sau o bucșă protejează cablul și ajută la menținerea compartimentării la foc, acolo unde este necesar.',
  },
  'nia-03-012': {
    explanation:
      'O intersecție în unghi drept minimizează expunerea paralelă dintre cabluri. Traseele paralele lungi cresc cuplajul EMI, chiar și atunci când este necesară o singură trecere.',
  },
  'nia-03-013': {
    explanation:
      'O conductă care este prea plină, are prea multe curbe sau are puncte de tragere limitate poate suprasolicita cablul în timpul instalării. Acești factori trebuie verificați înainte de tragere.',
  },
  'nia-03-014': {
    explanation:
      'Rutele existente pot fi supraîncărcate, deteriorate, blocate sau nu mai sunt adecvate. Un scurt studiu înainte de trasarea noilor cabluri evită deteriorarea serviciilor existente.',
  },
  'nia-03-015': {
    explanation:
      'Contaminarea la capătul cablului poate afecta terminarea ulterioară și rezultatele testelor. Capacele sau pungile păstrează capetele curate până când terminația este gata.',
  },
  'nia-03-016': {
    explanation:
      'Identificarea ambelor capete înainte de terminare previne conexiunile încrucișate și economisește lucrări suplimentare în timpul testării. Etichetele finale pot fi aplicate la terminare.',
  },
  'nia-03-017': {
    explanation:
      'Strivirea modifică geometria cablului și poate cauza defecțiuni care nu sunt vizibile din exterior. Chiar și evenimentele de strivire de scurtă durată pot eșua testele de performanță.',
  },
  'nia-03-018': {
    explanation:
      'O secvență planificată face tragerea mai sigură, reduce frecarea și previne încurcăturile care pot deteriora mănunchiul.',
  },
  'nia-03-019': {
    explanation:
      'Ansamblurile preterminate sunt gata de conectare. Conectorii deteriorați înseamnă o legătură defectă, astfel încât este esențială protecția prin tragere.',
  },
  'nia-03-020': {
    explanation:
      'Inspecția înainte de terminare detectează daunele la timp, astfel încât legătura să nu fie certificată cu defecte ascunse.',
  },
  'nia-04-001': {
    explanation:
      'Netorsionarea excesivă la terminație crește diafonia și reduce performanțele NEXT/return loss. Fiecare categorie de cablu are o valoare maximă de netorsionare, de obicei foarte scurtă.',
  },
  'nia-04-002': {
    explanation:
      'Pentru cablajul de date, limita fasciculului menționat este de 24 de cabluri. Pachetele mai mari pot crește căldura, interferențele între fascicule și tensiunea de tracțiune.',
  },
  'nia-04-003': {
    explanation:
      'Fixarea cu cârlig și buclă poate fi eliberată și reaplicată fără a zdrobi cablul. Legăturile din nailon trase strâns riscă să deformeze cablul echilibrat.',
  },
  'nia-04-004': {
    explanation:
      'Rutarea cablurilor de conectare afectează identificarea, fluxul de aer și fiabilitatea. Cablurile prefabricate nu trebuie să fie tăiate și rezemate la fața locului.',
  },
  'nia-04-005': {
    explanation:
      'Fibra este mai sensibilă la îndoire decât cuprul. Bobinele, conductele și tăvile de gestionare a îndoirii mențin raza minimă de îndoire fără bucle ascuțite.',
  },
  'nia-04-006': {
    explanation:
      'Diferitele suporturi au nevoi diferite de manipulare. Gestionarea verticală și orizontală separată pentru fiecare tip păstrează instalația ușor de întreținut.',
  },
  'nia-04-007': {
    explanation:
      'Buclele de serviciu trebuie controlate astfel încât să nu blocheze fluxul de aer, să depășească limitele razei de curbură sau să creeze pericole de întreținere viitoare.',
  },
  'nia-04-008': {
    explanation:
      'Ultimii câțiva centimetri de cablu încă influențează performanța legăturii certificate. Prinderea sau îndoirea în spatele plăcii poate duce la eșecul testului.',
  },
  'nia-04-009': {
    explanation:
      'Barele de management ușurează presiunea mecanică asupra conectorilor și mențin cablurile la distanță de căile de ventilație ale echipamentelor.',
  },
  'nia-04-010': {
    explanation:
      'Blocarea fluxului de aer duce la creșterea temperaturii echipamentelor și la reducerea fiabilității. Pachetele de cabluri nu trebuie să stea niciodată peste grilele de admisie sau evacuare.',
  },
  'nia-04-011': {
    explanation:
      'O instalație ordonată nu poate fi menținută dacă identificarea este ascunsă, schimbată sau distrusă în timpul îmbrăcării.',
  },
  'nia-04-012': {
    explanation:
      'Scoaterea cablurilor individuale poate abrada tecile și perturba terminațiile existente. Pachetul trebuie deschis și reparat corespunzător.',
  },
  'nia-04-013': {
    explanation:
      'O reținere prea aproape de o terminație poate scoate conductorii din poziție sau poate tensiona intrarea. Un mic decalaj menține terminația stabilă.',
  },
  'nia-04-014': {
    explanation:
      'Cablurile de categorie superioară au nevoie în continuare de geometrie, constrângere și identificare corecte. Câștigurile de performanță se pierd rapid dacă nu se respectă disciplina de îmbrăcare.',
  },
  'nia-05-001': {
    explanation:
      'Sistemul CPR / EuroClass este cadrul produselor de construcție utilizat pentru clasificarea reacției la foc a cablurilor (EN 13501-6). Ordinul privind siguranța împotriva incendiilor și reglementările privind construcțiile se situează la un nivel superior.',
  },
  'nia-05-002': {
    explanation:
      'CPR este Regulamentul privind produsele pentru construcții, care stabilește cadrul armonizat pentru performanța declarată a produselor, inclusiv reacția la foc pentru cabluri.',
  },
  'nia-05-003': {
    explanation:
      'Cca-s1b,d2,a2 este codul EuroClass utilizat de obicei pentru noile instalații fixe de cablu de date. Aca este necombustibil (rar pentru telecomunicații), iar Fca este cea mai scăzută clasificare.',
  },
  'nia-05-004': {
    explanation:
      'Eticheta cu marcajul CE de pe ambalaj este locul obligatoriu pentru clasificarea EuroClass. Site-urile web și fișele tehnice o pot conține și ele, însă eticheta este referința de control.',
  },
  'nia-05-005': {
    explanation:
      'Înregistrările privind izolarea împotriva incendiilor susțin strategia de apărare împotriva incendiilor a clădirii și demonstrează că compartimentările au fost restabilite corect.',
  },
  'nia-05-006': {
    explanation:
      'Performanța de blocare a incendiilor se bazează pe sisteme testate. Combinațiile improvizate de produse invalidează ratingul testat.',
  },
  'nia-05-007': {
    explanation:
      'Chiar și spațiile mici permit răspândirea fumului și ruperea compartimentării. Etanșarea trebuie să utilizeze sistemul specificat, nu materiale improvizate.',
  },
  'nia-05-008': {
    explanation:
      'Cablul instalat trebuie să poată fi urmărit în conformitate cu cerințele proiectului prin intermediul marcajului EuroClass de pe ambalaj sau manta și al DoP furnizate.',
  },
  'nia-05-009': {
    explanation:
      'Puțurile protejate fac parte din strategia împotriva incendiilor a clădirii. Lucrările de cablare nu trebuie să deterioreze construcția puțului sau compartimentarea acestuia.',
  },
  'nia-05-010': {
    explanation:
      'Sistemele de siguranță a vieții nu trebuie deteriorate fără autorizația corespunzătoare. O procedură de izolare documentată protejează ocupanții clădirii și instalatorul.',
  },
  'nia-05-011': {
    explanation:
      'Cablurile neutilizate sporesc sarcina de incendiu și pot induce în eroare viitorii lucrători. Îndepărtarea sau punerea în siguranță trebuie să respecte domeniul de aplicare al proiectului și strategia în caz de incendiu.',
  },
  'nia-05-012': {
    explanation:
      'Înlocuirea elementelor de fixare poate invalida certificarea sigiliului la testul la foc. Sistemul trebuie să fie instalat conform testelor.',
  },
  'nia-05-013': {
    explanation:
      'Odată ce ascunzătorile se închid, sigiliile lipsă sau defecte sunt dificil și costisitor de găsit și remediat. Inspecția trebuie să aibă loc înainte de închidere.',
  },
  'nia-05-014': {
    explanation:
      'Defectele de securitate la incendiu nu trebuie lăsate în seama soluționării informale sau ascunse la predare. Un raport formal sprijină remedierea și pista de audit.',
  },
  'nia-06-001': {
    explanation:
      'Controlul tamburului este o sarcină separată de tragere. O persoană controlează viteza și depășirea tamburului; cel puțin o altă persoană gestionează tragerea.',
  },
  'nia-06-002': {
    explanation:
      'Deteriorarea prin frecare indică, de obicei, un punct dur sau ascuțit al traseului. Continuarea va deteriora mai mult cablul, iar deteriorarea tecii poate fi un semn de deteriorare mai profundă.',
  },
  'nia-06-003': {
    explanation:
      'Un tambur grav deteriorat înseamnă că nu se poate avea încredere în cablul din interior. Tamburul nu trebuie utilizat pentru instalare și certificare.',
  },
  'nia-06-004': {
    explanation:
      'Așchiile reprezintă un pericol de rănire și de deteriorare a cablurilor. Cu pericolul controlat, tamburul poate fi utilizat dacă cablul în sine nu este deteriorat.',
  },
  'nia-06-005': {
    explanation:
      'Suporturile de tambur improvizate sunt nesigure și se pot prăbuși în timpul tragerii. Un cadru în formă de A și o axă corespunzătoare suportă greutatea tamburului și permit o rotație controlată.',
  },
  'nia-06-006': {
    explanation:
      'Manipularea manuală depinde de mărimea tamburului, de greutate, de traseu, de distanță și de individ. Evaluarea riscurilor, și nu un număr fix, determină decizia.',
  },
  'nia-06-007': {
    explanation:
      'Cutiile prăbușite creează pericole de împiedicare și tragere și pot încurca cablurile. Zona de lucru trebuie să fie securizată înainte de a continua.',
  },
  'nia-06-008': {
    explanation:
      'Minim două persoane: una care alimentează cutia, una care trage. Se adaugă alte persoane atunci când obstacolele de pe traseu necesită un control suplimentar.',
  },
  'nia-06-009': {
    explanation:
      'O persoană la colț reduce frecarea, controlează raza de îndoire și menține cablul în mișcare vizibil pentru echipă.',
  },
  'nia-06-010': {
    explanation:
      'Uneltele de decupare și tăiere special concepute reduc atât riscul de rănire, cât și deteriorarea cablurilor. Cuțitele sunt o ultimă soluție.',
  },
  'nia-06-011': {
    explanation:
      'Minimul tipic este de trei persoane: una la cutie, una care alimentează traseul și una la recepție.',
  },
  'nia-06-012': {
    explanation:
      'Tijele de cablu sunt concepute pentru a fi împinse prin trasee și îmbinate după cum este necesar. Articolele improvizate pot deteriora cablul sau se pot bloca în traseu.',
  },
  'nia-06-013': {
    explanation:
      'Azbestul suspect nu trebuie să fie deranjat fără un studiu și controale corecte. Procedura de la fața locului determină pașii următori.',
  },
  'nia-06-014': {
    explanation:
      'Firul de aramidă tocește rapid foarfecele obișnuite. Foarfecele Kevlar special concepute taie curat, fără să alunece sau să deterioreze fibra.',
  },
  'nia-06-015': {
    explanation:
      'Lamele de ferăstrău sunt concepute pentru a tăia pe cursa înainte. Montarea lor în sens invers reduce eficiența tăierii și crește riscul de rupere.',
  },
  'nia-06-016': {
    explanation:
      'Cutterele laterale taie curat conductorii de cupru cu diametru mic și învelișul cablului. Un ferăstrău mecanic sau un ferăstrău circular este supradimensionat pentru această lucrare.',
  },
  'nia-06-017': {
    explanation:
      'Un marker permanent cu vârf fin supraviețuiește manipulării în timpul tragerii. Marcajele cu vârf de pâslă, pix și cretă se șterg prea ușor.',
  },
  'nia-06-018': {
    explanation:
      'Dispozitivele de fixare cu cârlig și buclă pot fi eliberate și reaplicate fără a zdrobi cablul, ceea ce le face ideale pentru îmbrăcarea lucrărilor care pot fi încă ajustate.',
  },
  'nia-06-019': {
    explanation:
      'Decupatoarele special concepute controlează adâncimea de tăiere și reduc deteriorarea perechilor interioare și a foliilor. Cuțitele și foarfecele taie cu ușurință prea adânc.',
  },
  'nia-06-020': {
    explanation:
      'Cablul instalat poate fi deteriorat pe șantier înainte de predare. Protecția fizică și semnalizarea clară reduc acest risc.',
  },
  'nia-07-001': {
    explanation:
      'EN 420 stabilește cerințele generale pentru mănușile de protecție. Potrivirea, dexteritatea și adecvarea la sarcină sunt toate importante.',
  },
  'nia-07-002': {
    explanation:
      'EIP este un echipament de protecție individuală. Este ultima linie de apărare și protejează purtătorul.',
  },
  'nia-07-003': {
    explanation:
      'O scară înclinată trebuie așezată astfel încât baza să fie la o unitate în afară pentru fiecare patru unități de înălțime - aproximativ 75°.',
  },
  'nia-07-004': {
    explanation:
      'Atunci când sunt folosite ambele mâini, stabilitatea necesită încă trei puncte de contact. Corpul, genunchiul sau șoldul pot acționa ca al treilea punct.',
  },
  'nia-07-005': {
    explanation:
      'Azbestul suspect nu trebuie să fie deranjat. Zona trebuie să fie controlată în timp ce procedura privind azbestul de la fața locului se aplică.',
  },
  'nia-07-006': {
    explanation:
      'Caracterul adecvat al EPI rezultă din evaluarea riscurilor și din condițiile din ziua respectivă. Confortul și marca nu sunt criterii de selecție.',
  },
  'nia-07-007': {
    explanation:
      'Pe un șantier de construcții există mai multe pericole în același timp. În mod normal, pentru tragerea cablurilor este necesar un set complet de EPI.',
  },
  'nia-07-008': {
    explanation:
      'BS EN 397 este standardul pentru căștile de protecție industriale. Marca și culoarea sunt identificatori organizaționali, nu grade de protecție.',
  },
  'nia-07-009': {
    explanation:
      'Angajatorii trebuie să furnizeze gratuit un echipament de protecție individuală adecvat în cazul în care evaluarea riscurilor identifică necesitatea acestuia.',
  },
  'nia-07-010': {
    explanation:
      'O verificare vizuală înainte de utilizare de către utilizator detectează defectele evidente între inspecțiile formale.',
  },
  'nia-07-011': {
    explanation:
      'Raportarea accidentelor iminente este cea mai simplă modalitate de a preveni repetarea incidentelor înainte ca cineva să fie rănit.',
  },
  'nia-07-012': {
    explanation:
      'Expunerea la zgomot poate proveni de la activități de foraj, tăiere sau din apropiere. Evaluarea zgomotului determină cerința.',
  },
  'nia-07-013': {
    explanation:
      'Controlul prafului trebuie să fie prevăzut înainte de începerea sarcinii. Ierarhia este eliminarea, controlul la sursă, apoi PPE.',
  },
  'nia-07-014': {
    explanation:
      'Echipamentul de acces trebuie să fie în condiții de siguranță și adecvat pentru sarcină și încărcătură.',
  },
  'nia-07-015': {
    explanation:
      'Instalatorii trebuie să aibă în vedere siguranța celorlalți, nu numai a propriei echipe. În mod normal, este necesară separarea fizică.',
  },
  'nia-07-016': {
    explanation:
      'Unele produse necesită mănuși, ventilație, protecție pentru ochi sau eliminare specială. Fișa cu date de securitate (FDS) enumeră controalele.',
  },
  'nia-07-017': {
    explanation:
      'Accesul rapid la primul ajutor este important atunci când apar tăieturi, leziuni oculare sau căderi. Aceste măsuri ar trebui să facă obiectul instructajului la fața locului.',
  },
  'nia-07-018': {
    explanation:
      'O declarație de metodă rămâne valabilă doar atât timp cât condițiile reale corespund planului. Modificările semnificative necesită revizuire.',
  },
  'nia-07-019': {
    explanation:
      'Distragerea atenției de la telefon este un factor recunoscut care contribuie la împiedicări, căderi și răniri provocate de unelte. Regulile de pe șantier restricționează în mod normal utilizarea în anumite zone.',
  },
  'nia-07-020': {
    explanation:
      'Menținerea curățeniei la sfârșitul sarcinii previne pericolele pentru alți lucrători și utilizatori ai clădirii care intră ulterior în zonă.',
  },
  'nia-08-001': {
    explanation:
      'În cazul în care detaliile cablului IT nu sunt cunoscute, ghidul utilizează 200 mm ca distanță minimă prudentă față de cablul de alimentare.',
  },
  'nia-08-002': {
    explanation: 'Pentru acest scenariu fără separare, cu putere ecranată, lungimea maximă este de 35 m.',
  },
  'nia-08-003': {
    explanation:
      'Pentru coloana vertebrală ecranată situată lângă o sursă de alimentare neecranată fără separator, separarea minimă utilizată este de 50 mm.',
  },
  'nia-08-004': {
    explanation:
      'O încrucișare în unghi drept minimizează expunerea paralelă între cabluri și EMI-ul rezultat.',
  },
  'nia-08-005': {
    explanation:
      'Corpurile de iluminat fluorescente pot fi o sursă semnificativă de EMI. Ghidul utilizează 130 mm ca distanță minimă.',
  },
  'nia-08-006': {
    explanation:
      'Separarea protejează atât performanța transmisiei, cât și siguranța personală, deoarece tensiunea indusă pe cablul de telecomunicații poate deveni un pericol de șoc.',
  },
  'nia-08-007': {
    explanation:
      'Cuplajul EMI crește odată cu curentul din cablul de alimentare și scade odată cu distanța de la cablul de telecomunicații. Cifra de 50 mm presupune condiții tipice.',
  },
  'nia-08-008': {
    explanation:
      'Ecranarea, izolarea metalică și separarea fizică reduc toate EMI. UTP simplu în sine nu este o metodă de control EMI.',
  },
  'nia-08-009': {
    explanation: 'HSG47 ("Avoiding danger from underground services") este ghidul HSE relevant.',
  },
  'nia-08-010': {
    explanation:
      'Lucrul la înălțime se aplică numai în cazul în care există riscul de cădere (de exemplu, gropile adânci). Lucrările obișnuite de întreținere îngropată intră în principal sub incidența CDM, PSR și a regulamentelor de gestionare.',
  },
  'nia-08-011': {
    explanation:
      'Camerele pot conține gaze periculoase invizibile. Este necesară testarea gazelor înainte de intrare, adesea ca parte a unei proceduri pentru spații închise.',
  },
  'nia-08-012': {
    explanation:
      'Galbenul este asociat cu gazul și nu este utilizat pentru conductele de telecomunicații. Albul, negrul și griul sunt culorile tipice pentru conductele de telecomunicații.',
  },
  'nia-08-013': {
    explanation: 'Sub un trotuar, BS EN 50174-3 Tabelul 3 stabilește o adâncime minimă de 500 mm.',
  },
  'nia-08-014': {
    explanation:
      'O izolație metalică lipită corect poate acționa ca un ecran, reducând mediul EMI din jurul cablării.',
  },
  'nia-08-015': {
    explanation: 'Sub un drum sau carosabil, BS EN 50174-3 Tabelul 3 stabilește o adâncime minimă de 600 mm.',
  },
  'nia-09-001': {
    explanation:
      'Politica de gestionare a deșeurilor de pe amplasament este obligatorie și controlează calea de eliminare pentru fiecare flux de deșeuri.',
  },
  'nia-09-002': {
    explanation:
      'Chiar și în cazul în care cartonul pare reciclabil, politica site-ului determină traseul corect de colectare.',
  },
  'nia-09-003': {
    explanation:
      'Deșeurile de cablu pot fi reciclabile sau pot face obiectul unui contract specific amplasamentului. Politica decide calea de eliminare.',
  },
  'nia-09-004': {
    explanation:
      'Fragmentele de fibre sunt un flux de deșeuri specializat. Acestea nu trebuie golite în pubelele de reciclare generală sau mixtă.',
  },
  'nia-09-005': {
    explanation:
      'Multe amplasamente returnează butoaiele furnizorului pentru reutilizare sau utilizează o cale de eliminare definită. Nu improvizați în afara politicii.',
  },
  'nia-09-006': {
    explanation:
      'Cuprul este un material valoros, recuperabil. Politica amplasamentului impune în mod normal segregarea într-un flux de metale, nu în fluxul general.',
  },
  'nia-09-007': {
    explanation:
      'Containerele neetichetate pot duce la contaminarea încrucișată între fluxurile de deșeuri și la eliminarea incorectă. Acestea trebuie să fie identificate înainte de utilizare.',
  },
  'nia-09-008': {
    explanation:
      'Containerele care conțineau solvenți sau alte substanțe chimice sunt clasificate în mod normal ca deșeuri periculoase, chiar și atunci când sunt "goale".',
  },
  'nia-09-009': {
    explanation:
      'Tăieturile rămase în goluri cresc sarcina de foc și pot fi confundate ulterior cu cablurile instalate. Acestea trebuie să fie recuperate și eliminate în mod corespunzător.',
  },
  'nia-09-010': {
    explanation:
      'Ierarhia deșeurilor direcționează amplasamentele către prevenirea deșeurilor în primul rând și tratarea eliminării ca ultimă opțiune. Aceasta se aplică ambalajelor, resturilor și stocurilor deteriorate.',
  },
  'nia-09-011': {
    explanation:
      'Reutilizarea se situează deasupra reciclării în ierarhia deșeurilor. Returnarea stocurilor deteriorate previne, în primul rând, risipa.',
  },
  'nia-09-012': {
    explanation:
      'O notă de transfer al deșeurilor înregistrează traseul datoriei de îngrijire pentru deșeurile care părăsesc un amplasament. Câmpurile standard includ descrierea, cantitatea și părțile.',
  },
  'nia-09-013': {
    explanation:
      'Regulamentul DEEE reglementează deșeurile de echipamente electrice și electronice, inclusiv hardware-ul de rețea activ care este îndepărtat în timpul unei reamenajări.',
  },
  'nia-09-014': {
    explanation:
      'Deversările de solvenți necesită izolarea și eliminarea corespunzătoare a absorbantului contaminat. Evacuarea la canalizare este în mod normal interzisă și poate constitui o infracțiune.',
  },
  'nia-09-015': {
    explanation:
      'Reutilizarea stocului utilizabil este rezultatul preferat. Eliminarea materialului utilizabil este o risipă și poate încălca așteptările privind obligația de îngrijire.',
  },
};
